import numpy as np
import random
import torch
from torch_geometric.data import Data
from torch_geometric.transforms import RandomLinkSplit
import os

# It loads a .txt JSP and converts it to "np.array" format
def load_jsp_txt(path: str) -> np.ndarray:

    with open(path, "r") as f:
        lines = [l.strip() for l in f if l.strip()]
    jobs = lines[1:]
    sf_array = np.array([list(map(int, row.split())) for row in jobs])

    n_jobs, two_m = sf_array.shape
    n_machines = two_m // 2

    machine_order = np.zeros((n_jobs, n_machines), dtype=int)
    durations = np.zeros((n_jobs, n_machines), dtype=int)

    for i in range(two_m):
        if i % 2 == 0:
            machine_order[i // 2] = sf_array[:, i]
        else:
            durations[i // 2] = sf_array[:, i]

    jsp = np.stack([machine_order, durations])
    return jsp

# Generates a random JSP instance 
def generate_jsp_instance(n_jobs: int, n_machines: int, min_processing_time: int = 2, max_processing_time: int = 20) -> (np.array, np.array):
    """
    generates a singe jsp instance and saves it in Taillard-specification (http://jobshop.jjvh.nl/explanation.php)
    and saves it in a subdirectory (according to the size of the jsp) in the custom instance folder.
    See `jss_utils.PATHS`

    the order of the machines for the jobs and the duration of the task within a job are chosen randomly.

    the name is generated by the `jss_util.name_generator.generate_name`-fuction.

    :param n_jobs:              number of jobs
    :param n_machines:          number of machines
    :param min_processing_time: minimal duration of a task within a job
    :param max_processing_time: maximal duration of a task within a job

    :return:                    jsp as numpy array, Taillard style jsp numpy array

    """
    print(f"generating jsp instance of size ({n_jobs}, {n_machines}) (#jobs, #machines).")
    machine_order = [
        random.sample(list(range(0, n_machines)), n_machines) for _ in range(n_jobs)
    ]
    processing_times = [
        [random.randint(min_processing_time, max_processing_time) for m in range(n_machines)] for _ in range(n_jobs)
    ]

    specified_jsp = np.array([machine_order, processing_times])

    return specified_jsp

# Reads the .npz data and converts it torch readable format
def npz_to_data_list(npz_path: str) -> list[Data]:
    data = np.load(npz_path)
    A_all = data["A"]  # (N, T, T)
    X_all = data["X"]  # (N, T, F)

    data_list = []
    for i in range(A_all.shape[0]):
        A = A_all[i]
        X = X_all[i]

        src, dst = np.nonzero(A > 0)
        edge_index = torch.tensor(np.stack([src, dst], axis=0), dtype=torch.long)
        x = torch.tensor(X, dtype=torch.float)

        data_list.append(Data(x=x, edge_index=edge_index))
    return data_list

# Train, validation, test split
def split_for_link_pred(data_list: list[Data], val_ratio: float, test_ratio: float, is_undirected: bool) -> tuple[list[Data], list[Data], list[Data]]:
    
    splitter = RandomLinkSplit(
        num_val=val_ratio,
        num_test=test_ratio,
        is_undirected=is_undirected,
        add_negative_train_samples=False,
    )

    train_list, val_list, test_list = [], [], []
    for d in data_list:
        tr, va, te = splitter(d)
        train_list.append(tr)
        val_list.append(va)
        test_list.append(te)

    return train_list, val_list, test_list