import numpy as np
import random
import torch
from torch_geometric.data import Data
from torch_geometric.utils import degree

# It loads a .txt JSP and converts it to "np.array" format
def load_jsp_txt(path: str) -> np.ndarray:

    with open(path, "r") as f:
        lines = [l.strip() for l in f if l.strip()]
    jobs = lines[1:]
    sf_array = np.array([list(map(int, row.split())) for row in jobs])

    n_jobs, two_m = sf_array.shape
    n_machines = two_m // 2

    machine_order = np.zeros((n_jobs, n_machines), dtype=int)
    durations = np.zeros((n_jobs, n_machines), dtype=int)

    for i in range(two_m):
        if i % 2 == 0:
            machine_order[i // 2] = sf_array[:, i]
        else:
            durations[i // 2] = sf_array[:, i]

    jsp = np.stack([machine_order, durations])
    return jsp

# Generates a random JSP instance 
def generate_jsp_instance(n_jobs: int, n_machines: int, min_processing_time: int = 2, max_processing_time: int = 100) -> (np.array, np.array):
    """
    generates a singe jsp instance and saves it in Taillard-specification (http://jobshop.jjvh.nl/explanation.php)
    and saves it in a subdirectory (according to the size of the jsp) in the custom instance folder.
    See `jss_utils.PATHS`

    the order of the machines for the jobs and the duration of the task within a job are chosen randomly.

    the name is generated by the `jss_util.name_generator.generate_name`-fuction.

    :param n_jobs:              number of jobs
    :param n_machines:          number of machines
    :param min_processing_time: minimal duration of a task within a job
    :param max_processing_time: maximal duration of a task within a job

    :return:                    jsp as numpy array, Taillard style jsp numpy array

    """
    print(f"generating jsp instance of size ({n_jobs}, {n_machines}) (#jobs, #machines).")
    machine_order = [
        random.sample(list(range(0, n_machines)), n_machines) for _ in range(n_jobs)
    ]
    processing_times = [
        [random.randint(min_processing_time, max_processing_time) for m in range(n_machines)] for _ in range(n_jobs)
    ]

    specified_jsp = np.array([machine_order, processing_times])

    return specified_jsp

def npz_to_data_list(npz_path: str) -> list[Data]:
    data = np.load(npz_path)
    A_all = data["A"]          # (N, T, T)
    X_all = data["X"]          # (N, T, F)
    M_all = data["M"]          # (N, T)  machine ids
    n_jobs = int(data["n_jobs"][0])
    n_machines = int(data["n_machines"][0])

    data_list = []

    for i in range(A_all.shape[0]):
        A = A_all[i]
        X = X_all[i]
        M = M_all[i]                     # (T,)

        T = A.shape[0]

        # ---------- build edge_index ----------
        src, dst = np.nonzero(A > 0)
        edge_index = torch.tensor(
            np.stack([src, dst], axis=0),
            dtype=torch.long
        )

        # ---------- add job one-hot ----------
        job_id = np.arange(T) // n_machines
        job_oh = np.eye(n_jobs, dtype=np.float32)[job_id]

        X_aug = np.concatenate([X, job_oh], axis=1)

        # ---------- precedence edges (same job only) ----------
        prec_src = []
        prec_dst = []
        for j in range(n_jobs):
            start = j * n_machines
            for k in range(n_machines - 1):
                prec_src.append(start + k)
                prec_dst.append(start + k + 1)

        precedence_edge_index = torch.tensor(
            [prec_src, prec_dst],
            dtype=torch.long
        )

        data_list.append(
            Data(
                x=torch.tensor(X_aug, dtype=torch.float),
                edge_index=edge_index,
                machine=torch.tensor(M, dtype=torch.long).argmax(dim=1).long(),
                precedence_edge_index=precedence_edge_index
            )
        )

    return data_list

# Train, validation, test split
def split_for_link_pred(data_list: list[Data], val_ratio: float, test_ratio: float) -> tuple[list[Data], list[Data], list[Data]]:
    
    random.seed(42)
    data_list = data_list.copy()
    random.shuffle(data_list)

    n = len(data_list)
    n_test = int(n * test_ratio)
    n_val  = int(n * val_ratio)
    n_train = n - n_val - n_test

    train_list = data_list[:n_train]
    val_list   = data_list[n_train:n_train + n_val]
    test_list  = data_list[n_train + n_val:]

    return train_list, val_list, test_list

def edge_diff(edge_a, edge_b):
    """
    returns edges in edge_a that are not in edge_b
    """
    set_a = set(map(tuple, edge_a.t().tolist()))
    set_b = set(map(tuple, edge_b.t().tolist()))

    diff = list(set_a - set_b)

    if len(diff) == 0:
        return torch.empty((2, 0), dtype=torch.long)

    return torch.tensor(diff, dtype=torch.long).t()

def edge_sort(edges):
    src = edges[0]
    dst = edges[1]
    max_node = int(edges.max()) + 1
    key = src * max_node + dst
    order = torch.argsort(key)
    edges_sorted = edges[:, order]
    return edges_sorted

def compute_pna_degree_histogram(data_list):
    max_degree = 0

    for data in data_list:
        d = degree(data.edge_index[1], num_nodes=data.num_nodes, dtype=torch.long)
        max_degree = max(max_degree, int(d.max()))

    deg = torch.zeros(max_degree + 1, dtype=torch.long)

    for data in data_list:
        d = degree(data.edge_index[1], num_nodes=data.num_nodes, dtype=torch.long)
        deg += torch.bincount(d, minlength=deg.numel())

    return deg